const HUMAN_COLOUR = "red";
const COMPUTER_COLOUR = "yellow";
const MOBILE_DISC_RADIUS = 20;
const GAMEBOARD_WIDTH = 7;
const GAMEBOARD_HEIGHT = 6;

const COMPUTER_DELAY = 1500;

export {
  GAMEBOARD_HEIGHT,
  GAMEBOARD_WIDTH,
  HUMAN_COLOUR,
  COMPUTER_COLOUR,
  MOBILE_DISC_RADIUS,
  COMPUTER_DELAY,
};
