/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const ClassicLazyRouteImport = createFileRoute('/classic')()
const BlindfoldLazyRouteImport = createFileRoute('/blindfold')()

const ClassicLazyRoute = ClassicLazyRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/classic.lazy').then((d) => d.Route))
const BlindfoldLazyRoute = BlindfoldLazyRouteImport.update({
  id: '/blindfold',
  path: '/blindfold',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blindfold.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blindfold': typeof BlindfoldLazyRoute
  '/classic': typeof ClassicLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blindfold': typeof BlindfoldLazyRoute
  '/classic': typeof ClassicLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blindfold': typeof BlindfoldLazyRoute
  '/classic': typeof ClassicLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blindfold' | '/classic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blindfold' | '/classic'
  id: '__root__' | '/' | '/blindfold' | '/classic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlindfoldLazyRoute: typeof BlindfoldLazyRoute
  ClassicLazyRoute: typeof ClassicLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blindfold': {
      id: '/blindfold'
      path: '/blindfold'
      fullPath: '/blindfold'
      preLoaderRoute: typeof BlindfoldLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlindfoldLazyRoute: BlindfoldLazyRoute,
  ClassicLazyRoute: ClassicLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
