/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ClassicLazyRouteImport = createFileRoute('/classic')()
const BlindfoldLazyRouteImport = createFileRoute('/blindfold')()

const ClassicLazyRoute = ClassicLazyRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/classic.lazy').then((d) => d.Route))
const BlindfoldLazyRoute = BlindfoldLazyRouteImport.update({
  id: '/blindfold',
  path: '/blindfold',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blindfold.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blindfold': typeof BlindfoldLazyRoute
  '/classic': typeof ClassicLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blindfold': typeof BlindfoldLazyRoute
  '/classic': typeof ClassicLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blindfold': typeof BlindfoldLazyRoute
  '/classic': typeof ClassicLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/blindfold' | '/classic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/blindfold' | '/classic'
  id: '__root__' | '/' | '/about' | '/blindfold' | '/classic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlindfoldLazyRoute: typeof BlindfoldLazyRoute
  ClassicLazyRoute: typeof ClassicLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blindfold': {
      id: '/blindfold'
      path: '/blindfold'
      fullPath: '/blindfold'
      preLoaderRoute: typeof BlindfoldLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blindfold': {
      id: '/blindfold'
      path: '/blindfold'
      fullPath: '/blindfold'
      preLoaderRoute: typeof BlindfoldLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/about' {
  const createFileRoute: CreateFileRoute<
    '/about',
    FileRoutesByPath['/about']['parentRoute'],
    FileRoutesByPath['/about']['id'],
    FileRoutesByPath['/about']['path'],
    FileRoutesByPath['/about']['fullPath']
  >
}
declare module './routes/blindfold.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/blindfold']['preLoaderRoute']
  >
}
declare module './routes/classic.lazy' {
  const createLazyFileRoute: CreateLazyFileRoute<
    FileRoutesByPath['/classic']['preLoaderRoute']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlindfoldLazyRoute: BlindfoldLazyRoute,
  ClassicLazyRoute: ClassicLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
